// fifo_81b_32d.v

// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module fifo_81b_32d (
		input  wire [80:0] data,  //  fifo_input.datain,  Data input of the memory.The data port is required for all FIFO operation.
		input  wire        wrreq, //            .wrreq,   wrreq input signal to request for write operation.The wrreq signal is required for all FIFO operation.
		input  wire        rdreq, //            .rdreq,   rdreq input signal to request for read operation.The rdreq signal is required for all FIFO operation.
		input  wire        clock, //            .clk,     Positive-edge-triggered clock.
		input  wire        sclr,  //            .sclr,    It is synchronous reset.Assert this signal to clear all the output status ports, but the effect on the q output may vary for different FIFO configurations.
		output wire [80:0] q,     // fifo_output.dataout, Data output of the memory. This port is required for all FIFO operation.
		output wire [4:0]  usedw, //            .usedw,   Show the number of words stored in the FIFO.
		output wire        full,  //            .full,    When full signal is asserted, the FIFO IP core is considered full. Do not perform write request operation when the FIFO IP core is full.
		output wire        empty  //            .empty,   When empty signal is asserted, the FIFO IP core is considered empty.Do not perform read request operation when the FIFO IP core is empty.
	);

	fifo_81b_32d_fifo_1941_xbievyq fifo_0 (
		.data  (data),  //   input,  width = 81,  fifo_input.datain
		.wrreq (wrreq), //   input,   width = 1,            .wrreq
		.rdreq (rdreq), //   input,   width = 1,            .rdreq
		.clock (clock), //   input,   width = 1,            .clk
		.sclr  (sclr),  //   input,   width = 1,            .sclr
		.q     (q),     //  output,  width = 81, fifo_output.dataout
		.usedw (usedw), //  output,   width = 5,            .usedw
		.full  (full),  //  output,   width = 1,            .full
		.empty (empty)  //  output,   width = 1,            .empty
	);

endmodule
