// altecc_enc_latency0.v

// Generated using ACDS version 25.3 109

`timescale 1 ps / 1 ps
module altecc_enc_latency0 (
		input  wire [63:0] data, // data.data, Data input port. The size of the input port depends on the WIDTH_DATAWORD parameter value. The data port contains the raw data to be encoded.
		output wire [71:0] q     //    q.q,    Encoded data output port. The size of the output port depends on the WIDTH_CODEWORD parameter value.
	);

	altecc_enc_latency0_altecc_1918_qm2rhyy altecc_0 (
		.data (data), //   input,  width = 64, data.data
		.q    (q)     //  output,  width = 72,    q.q
	);

endmodule
