// w32_d1024.v

// Generated using ACDS version 24.3 212

`timescale 1 ps / 1 ps
module w32_d1024 (
		input  wire [31:0] data,      //      data.datain,    Data input of the memory.The data port is required for all RAM operation modes:SINGLE_PORT,DUAL_PORT,BIDIR_DUAL_PORT,QUAD_PORT
		output wire [31:0] q,         //         q.dataout,   Data output from the memory
		input  wire [9:0]  wraddress, // wraddress.wraddress, Write address input to the memory.
		input  wire [9:0]  rdaddress, // rdaddress.rdaddress, Read address input to the memory.
		input  wire        wren,      //      wren.wren,      Write enable input for address port.The wren signal is required for all RAM operation modes:SINGLE_PORT,DUAL_PORT,BIDIR_DUAL_PORT,QUAD_PORT
		input  wire        clock,     //     clock.clk,       Memory clock, refer to user guide for specific details
		input  wire        sclr       //      sclr.reset,     Synchronously clear the output ports. The synchronous clear effect on the registered ports can be controlled through their corresponding parameter, such as outdata_sclr_a and outdata_sclr_b.
	);

	w32_d1024_ram_2port_2050_e2optgi ram_2port_0 (
		.data      (data),      //   input,  width = 32,      data.datain
		.q         (q),         //  output,  width = 32,         q.dataout
		.wraddress (wraddress), //   input,  width = 10, wraddress.wraddress
		.rdaddress (rdaddress), //   input,  width = 10, rdaddress.rdaddress
		.wren      (wren),      //   input,   width = 1,      wren.wren
		.clock     (clock),     //   input,   width = 1,     clock.clk
		.sclr      (sclr)       //   input,   width = 1,      sclr.reset
	);

endmodule
