// (C) 2001-2024 Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions and other 
// software and tools, and its AMPP partner logic functions, and any output 
// files from any of the foregoing (including device programming or simulation 
// files), and any associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License Subscription 
// Agreement, Intel FPGA IP License Agreement, or other applicable 
// license agreement, including, without limitation, that your use is for the 
// sole purpose of programming logic devices manufactured by Intel and sold by 
// Intel or its authorized distributors.  Please refer to the applicable 
// agreement for further details.


//Legal Notice: (C)2023 Altera Corporation. All rights reserved.  Your
//use of Altera Corporation's design tools, logic functions and other
//software and tools, and its AMPP partner logic functions, and any
//output files any of the foregoing (including device programming or
//simulation files), and any associated documentation or information are
//expressly subject to the terms and conditions of the Altera Program
//License Subscription Agreement or other applicable license agreement,
//including, without limitation, that your use is for the sole purpose
//of programming logic devices manufactured by Altera and sold by Altera
//or its authorized distributors.  Please refer to the applicable
//agreement for further details.
// pcie_ed_MEM0.v

// Generated using ACDS version 22.1 174

`timescale 1 ps / 1 ps
module pcie_ed_MEM0 (
		input  wire          clk,        //   clk1.clk
		input  wire [7:0]    address,    //     s1.address
		input  wire          clken,      //       .clken
		input  wire          chipselect, //       .chipselect
		input  wire          write,      //       .write
		output wire [1023:0] readdata,   //       .readdata
		input  wire [1023:0] writedata,  //       .writedata
		input  wire [127:0]  byteenable, //       .byteenable
		input  wire          reset       // reset1.reset
	);

	pcie_ed_MEM0_altera_avalon_onchip_memory2_1932_vi4l4uq #(
//		.INIT_FILE ("pcie_ed_MEM0_MEM0.hex")
//		.INIT_FILE ("/nfs/site/disks/rnr_cxl_lvf_3/users/ochittur/mirror_ip_22june/icm/client_0.local/rnr_ial_sip/rtl/subIP/cxl_pio/pcie_pio_ed/pcie_ed_MEM0/pcie_ed_MEM0_MEM0.hex")
	) mem0 (
		.clk        (clk),        //   input,     width = 1,   clk1.clk
		.address    (address),    //   input,     width = 8,     s1.address
		.clken      (clken),      //   input,     width = 1,       .clken
		.chipselect (chipselect), //   input,     width = 1,       .chipselect
		.write      (write),      //   input,     width = 1,       .write
		.readdata   (readdata),   //  output,  width = 1024,       .readdata
		.writedata  (writedata),  //   input,  width = 1024,       .writedata
		.byteenable (byteenable), //   input,   width = 128,       .byteenable
		.reset      (reset),      //   input,     width = 1, reset1.reset
		.reset_req  (1'b0),       // (terminated),                       
		.freeze     (1'b0)        // (terminated),                       
	);

endmodule
`ifdef QUESTA_INTEL_OEM
`pragma questa_oem_00 "EtAh8aN7m2BPKOTfO5tEAbNSD19BnNEklF4xQRY7YZ2oRe/8wDIRx8XCKuwkXQtjYcM5gRXSD6c+oGX77mfnvlAGw9KTmnXPBu3GU7e3qFjUTrXWlEAN76gMqJTePk91Iv2qtpAKuY2LJHLiowUVDoSuAt1Csh1O2u7qDzQRIaeVL/AJWYDMfWERE2K26wZcHHB8eTbMnhSND4m01aQODfKXixyUFYBUVJCy/gZrUwD0lI+DWZeeeSFSmgqPPzkB0iwlHVM0wDOGaYyLWzyQHl4U4jQdDDtscbnqCTVYaO/y8yJjqC1KU8QR0A4/puve1MmaHqpK4jK/djtudW7IpHL3kMjIlA/k77PkiM5qE97jNlam1YqHqQftBRKaXoWciVCObA76nwmlACvbfhIgrHzLvjWzhKZsq1fLDfES3PWH2WVY+Pr620G1jDoN7Iwn3guyniDqBLmdWgGyKbLPV3sKmsRDmVJh5aNFhWwS0Q5HNAJIaphgi4Pmv/xclpCDygjJcZg8nqMtEuoQni7e2IP14pZxsFlLidFKU8wmwkqIN//r0PfJC/X7wiPKVjwQLKzKeksQIjGIdVJtlN1yD/rs/YUm10EYPNeFCbuXTXf1GVzhubg2seebdN0y/YB41/cdXaEdphQyCiWRArB3B9PdFazUbihqDQoT3kpg2avnw+6jUQtMgL9/uC9TpSJ1vmm8Aen1w7uia1lnuZ4LtVXidocdemL/CGK6m1dcFpQyvE3EtFlJl3ugUBTd7LIU2vUQDgJ4jG89KyrsMy0cUZ5dk8SAZwzyIzf43xo8bYiaA8OkfrbBrN8y1NHYH8hEUevZ/1avgbp7lMfv3N+KZZyBpGJ8wmFE2hMqAoGgJEKYZtQklwQs1WmLBF5KzqnOAVA3uJLPhowKmpN7U4osJElGhIr6a/hBCpnTrWgIs3TV+crZdvUUbFtHP6oY4EilRDor+6UhN6hUCBysDpk2IPKeXNNn8smsUTK5wXfAJ3tcDt/eNISX/eByzTHtzRli"
`endif