// fifo_36w_64d.v

// Generated using ACDS version 24.3 212

`timescale 1 ps / 1 ps
module fifo_36w_64d (
		input  wire [35:0] data,  //  fifo_input.datain,  Data input of the memory.The data port is required for all FIFO operation.
		input  wire        wrreq, //            .wrreq,   wrreq input signal to request for write operation.The wrreq signal is required for all FIFO operation.
		input  wire        rdreq, //            .rdreq,   rdreq input signal to request for read operation.The rdreq signal is required for all FIFO operation.
		input  wire        clock, //            .clk,     Positive-edge-triggered clock.
		output wire [35:0] q,     // fifo_output.dataout, Data output of the memory. This port is required for all FIFO operation.
		output wire [5:0]  usedw, //            .usedw,   Show the number of words stored in the FIFO.
		output wire        full,  //            .full,    When full signal is asserted, the FIFO IP core is considered full. Do not perform write request operation when the FIFO IP core is full.
		output wire        empty  //            .empty,   When empty signal is asserted, the FIFO IP core is considered empty.Do not perform read request operation when the FIFO IP core is empty.
	);

	fifo_36w_64d_fifo_1930_6vu5myi fifo_0 (
		.data  (data),  //   input,  width = 36,  fifo_input.datain
		.wrreq (wrreq), //   input,   width = 1,            .wrreq
		.rdreq (rdreq), //   input,   width = 1,            .rdreq
		.clock (clock), //   input,   width = 1,            .clk
		.q     (q),     //  output,  width = 36, fifo_output.dataout
		.usedw (usedw), //  output,   width = 6,            .usedw
		.full  (full),  //  output,   width = 1,            .full
		.empty (empty)  //  output,   width = 1,            .empty
	);

endmodule
