// pll_0.v

// Generated using ACDS version 23.3 104

`timescale 1 ps / 1 ps
module pll_0 (
		input  wire  inclk,       //       inclk.clk
		output wire  clock_div1x, // clock_div1x.clk
		output wire  clock_div2x, // clock_div2x.clk
		output wire  clock_div4x  // clock_div4x.clk
	);

	pll_0_intelclkctrl_200_wlyqxpa intelclkctrl_0 (
		.inclk       (inclk),       //   input,  width = 1,       inclk.clk
		.clock_div1x (clock_div1x), //  output,  width = 1, clock_div1x.clk
		.clock_div2x (clock_div2x), //  output,  width = 1, clock_div2x.clk
		.clock_div4x (clock_div4x)  //  output,  width = 1, clock_div4x.clk
	);

endmodule
